Testing
YunoHost-Apps/wireguard_ynh pull request #56
Opened 2022-02-20 22:59 UTC by tituspijean

Implement Tag's improvements:

- [x] #54 
- [ ] #55 

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-02-26 21:56 UTC, Tagadda approved these changes

2022-02-26 21:57 UTC, Tagadda reviewed
Package version bump ?

2022-02-26 23:20 UTC, tituspijean commented
!testme

2022-02-27 10:43 UTC, tituspijean commented
Sorry @Tagadda, but your fixes on the services do not work. I tried adding a new client, Apply config, start the VPN on the new client, and no, I still have to manually restart the WireGuard service. :/

2022-02-27 15:46 UTC, Tagadda commented on scripts/upgrade
> +
Should have been updated by https://github.com/YunoHost-Apps/wireguard_ynh/blob/aaad102c96c5144630c4a3d77df34316b5757557/scripts/upgrade#L194-L199, independently of this test I assume

2022-03-02 20:25 UTC, Tagadda requested changes

2022-03-02 20:25 UTC, Tagadda commented on scripts/_common.sh
> +interface=$(ip route | awk '/default/ { print $5 }' | head)
```suggestion
interface=$(ip route | awk '/default/ { print $5 }' | head -n1)
```

2022-03-04 16:54 UTC, tituspijean commented
!testme

2022-03-04 21:57 UTC, tituspijean commented
Thanks Tag!

2022-03-04 21:57 UTC, merged